### PR TITLE
Better Mobile Nav Styling

### PR DESCRIPTION
**Pull request by BraadMartin**
This is my first pass at the new mobile nav styling. It still needs work, and I plan on adding commits before we merge, so feel free to check it out but don't merge just yet.

The changes I've made here are currently having negative effects on the tablet and desktop nav styling. I'm happy to go ahead and deal with the issues in this PR, or I can focus on the mobile nav styles in this PR and we can assume there will be work to do for tablet and desktop styling after we merge.

I haven't yet tackled the various mobile nav style options that we have, and I want to get those into this PR before we merge. Currently this is just the base mobile nav styling that we'll cascade over with tweaks for the various style options.

If you have any thoughts about the implementation I'd love to hear them. I'm hoping I can get things finished up over the next few days as I know this is a priority. :)

### CODE REVIEW

**Comment by carrieforde** [comment]
Since this is a mobile-first theme, and the mobile nav styles are a high priority, I am happy to have this PR address just those. Once the styles are nailed down for mobile, they will be easier to deal with at other screen sizes.

I do have one thought about what you have so far. Right now, when a menu item has a sub-menu, there is a `-` to indicate this, and when that menu is expanded, there is a `+`. This seems a bit counter intuitive to me. I'd suggest either swapping it, or switching those out all together in favor of some thing like a [chevron down](http://fortawesome.github.io/Font-Awesome/icon/chevron-down/) and [chevron up](http://fortawesome.github.io/Font-Awesome/icon/chevron-up/) to open and close sub-menus respectively.

Otherwise, this is looking great. Please let me know if there is anything I can do to help!

**Comment by BraadMartin** [comment]
Your point about the + and - is interesting. For me I get the `+` when the sub menu is closed, and clicking it expands the sub menu and turns it to a `-`, which was making sense because I was thinking the `+` means expand. Maybe there is some difference in our setup that is causing us to see different things.

I definitely agree that switching to the chevrons like twentyfifteen is better than the `+` and `-`. In the JS you'll see that I'm assigning the icons to variables before using them, so it would be super easy to change them to whatever. I'll let you decide which chevrons to use after we merge this PR.

**Comment by BraadMartin** [comment]
This baby is ready for merge. There is lots of neat things in here that I'm excited to discuss. The tablet and above nav styles are naturally totally broken and waiting for you to fix. :0)

**Comment by carrieforde** [comment]
I like it. I think there are a few tweaks to be done (I noticed the nav close button is a few pixels off from the nav open, which probably doesn't bother most, but, of course, kinda bothers me), but I'll need to merge to test on my mobile devices. Very nice work.

**Pull request merged**
